apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      containers:
      - name: metrics-generator
        image: metric-gen:v12
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: redis-config
        ports:
        - containerPort: 5001 
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-generator-service
spec:
  selector:
    app: metrics-generator
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001