apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileparser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileparser
  template:
    metadata:
      labels:
        app: fileparser
    spec:
      containers:
      - name: fileparser
        image: fileparser:v1
        envFrom:
        - configMapRef:
            name: redis-config
        imagePullPolicy: Never
        ports:
        - containerPort: 5000 # Example port
---
apiVersion: v1
kind: Service
metadata:
  name: fileparser-service
spec:
  selector:
    app: fileparser
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000